manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml  # Wskazuje na główną konfigurację ZMK
  self:
    path: config  # Twoja lokalna konfiguracja
