name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup west
        run: pip3 install west

      - name: Init and update west
        run: west init -l . && west update

      - name: Build firmware
        run: |
          west build -s app -b corne_left -d build/left -- -DZMK_CONFIG="$(pwd)/config"
          west build -s app -b corne_right -d build/right -- -DZMK_CONFIG="$(pwd)/config"
